# Generated by Django 5.1.7 on 2025-04-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipofferletter',
            name='company_verified',
        ),
    ]
