# Generated by Django 5.2 on 2025-04-22 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_remove_department_advisors_assigned'),
        ('students', '0002_internshipofferletter_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipofferletter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.company'),
        ),
    ]
