# Generated by Django 5.2 on 2025-04-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='internship_year',
            field=models.PositiveIntegerField(blank=True, default=2025, null=True),
        ),
    ]
