# Generated by Django 5.2 on 2025-04-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_internship_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipofferletter',
            name='company',
        ),
    ]
