# Generated by Django 5.2 on 2025-04-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_internshipofferletter_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipofferletter',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
