# Generated by Django 5.2 on 2025-05-04 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_internshipofferletter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 3, 22, 14, 44, 893974)),
        ),
    ]
