# Generated by Django 5.2 on 2025-04-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='registration_end',
        ),
        migrations.RemoveField(
            model_name='department',
            name='registration_start',
        ),
    ]
