# Generated by Django 5.2 on 2025-04-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_remove_department_registration_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='advisors_assigned',
        ),
    ]
