# Generated by Django 5.2 on 2025-04-22 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_remove_department_advisors_assigned'),
        ('students', '0003_alter_internshipofferletter_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
