# Generated by Django 5.2 on 2025-04-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_remove_company_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshiphistory',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
