# Generated by Django 5.2 on 2025-04-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0007_alter_internshiphistory_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='report_submission_interval_days',
        ),
        migrations.RemoveField(
            model_name='department',
            name='required_reports_count',
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
