# Generated by Django 5.2 on 2025-04-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0008_remove_department_report_submission_interval_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
