# Generated by Django 5.2 on 2025-04-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0009_alter_company_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='telegram_id',
            field=models.CharField(default=3345, max_length=100),
            preserve_default=False,
        ),
    ]
