# Generated by Django 5.1.7 on 2025-04-01 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('university_email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Must be a valid university email')])),
            ],
        ),
    ]
