# Generated by Django 5.2 on 2025-04-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='number_of_expected_reports',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
