# Generated by Django 5.2 on 2025-04-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0003_advisor_report_submission_interval_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
