# Generated by Django 5.1.7 on 2025-04-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0004_remove_advisor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='university_email',
        ),
    ]
