# Generated by Django 5.2 on 2025-04-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0004_advisorlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisorlist',
            old_name='full_name',
            new_name='advfull_name',
        ),
    ]
