# Generated by Django 5.1.7 on 2025-04-02 15:59

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0005_remove_advisor_first_name_remove_advisor_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='university_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Must be a valid university email')]),
            preserve_default=False,
        ),
    ]
