# Generated by Django 5.2 on 2025-04-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0005_rename_full_name_advisorlist_advfull_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvisorList',
        ),
    ]
