# Generated by Django 5.2 on 2025-04-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0006_delete_advisorlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('invited_on', models.DateTimeField(auto_now_add=True)),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
    ]
