# Generated by Django 5.2 on 2025-04-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0007_advisorlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvisorList',
        ),
    ]
